-- ============================================================
-- AgroDemak - [DEPRECATED] UPDATE Syarat Tumbuh Komoditas
-- ============================================================
-- FILE INI SUDAH TIDAK DIPAKAI.
--
-- Sebelumnya berisi UPDATE parameter untuk komoditas dengan nama lama
-- ('Padi', 'Cabai', 'Kangkung') yang TIDAK konsisten dengan knowledge
-- base sistem pakar ('Padi Sawah', 'Cabai Keriting', 'Cabai Rawit').
--
-- Seed komoditas + library yang BENAR dan KONSISTEN ada di:
--     supabase_seed_library.sql
--
-- Jalankan urutan berikut di Supabase SQL Editor:
--   1. supabase_schema.sql            (struktur tabel dasar)
--   2. supabase_kalender_tanam.sql    (prediksi_iklim, threshold, cf_rule)
--   3. supabase_seed_library.sql      (10 komoditas fokus + artikel)
--
-- Jangan jalankan file ini lagi.
-- ============================================================
